homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 0
  longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include includes/customize.yaml
  
lovelace:
  mode: yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  server_port: 8123
  use_x_forwarded_for: True
  trusted_proxies:
    - 172.17.0.1
    - 127.0.0.1
  #trusted_networks:
  ip_ban_enabled: true #blocks unathorized ips from accessing HA
  login_attempts_threshold: 5 #number of attempts before ip is banned

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

#mqtt
mqtt:
  password: !secret mqtt_password
        
# Text to speech
tts:
  - platform: google

# Cloud
cloud:

python_script:
shopping_list:
  show: false

# telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret chat_id_1
      - !secret chat_id_2

tellduslive:
        #  public key: !secret public_key
        #  private key: !secret private_key
        #  token: !secret token
        #  token secret: !secret token_secret

notify: !include includes/notify.yaml
group: !include includes/groups.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
climate: !include includes/climate.yaml
shell_command: !include includes/shell_commands.yaml

panel_iframe:
  weather:
    title: Meisal
    icon: mdi:weather-snowy
    url: !secret meisal

