title: Hytta

views:

#Hovedmeny
  - id: Hjem
    title: Hjem
    cards:

      - id: klimasensorer
        type: entities
        show_header_toggle: false
        title: Moens klimapanel
        entities:          
          - sensor.aeotec_zw100_multisensor_6_temperature_3
          - sensor.smoke_sensor_temperature_stue
          - sensor.aeotec_zw100_multisensor_6_relative_humidity_3
          - sensor.stue_humidity
          - sensor.stue_temperature 
          - sensor.smoke_sensor_temperature_loftstue
          - sensor.ute_temperature

      - id: brytere
        type: entities
        show_header_toggle: false
        title: Brytere
        entities:
          - switch.fibaro_system_fgwpef_wall_plug_gen5_switch_3
          - switch.ovn_soverom
          - switch.ovn_stue_n
          - switch.ovn_stue_s
          - switch.d1
          
      - id: Termostat_stue
        type: thermostat
        show_header_toggle: false
        title: Stue
        entity: climate.stue

#Brann
  - id: Alarmsystem
    title: Alarm
    cards:
        
      - id: Brannalarm
        type: entities
        show_header_toggle: false
        title: Brann
        entities:
          - sensor.smoke_sensor_general_stue
          - sensor.smoke_sensor_heat_stue_1
          - sensor.smoke_sensor_smoke_stue_1
          - sensor.smoke_sensor_smoke_stue_2
          - sensor.smoke_sensor_smoke_loftstue_2
          - sensor.smoke_sensor_smoke_loftstue_1
      - id: Sensorstatus
        type: entities
        show_header_toggle: false
        title: Sensorstatus
        entities:
          - sensor.smoke_sensor_stue_batteri
          - sensor.smoke_sensor_loftstue_batteri

#Stromforbruk
  - id: Forbruk
    title: Stromforbruk
    cards:

      - id: effekt_sensorer      
        type: entities
        show_header_toggle: false
        title: Ovner
        entities:
          - sensor.fibaro_system_fgwpef_wall_plug_gen5_energy_2
          - sensor.fibaro_system_fgwpef_wall_plug_gen5_power_5

      - id: bryter_forbruk_graf
        type: sensor
        entity: sensor.fibaro_system_fgwpef_wall_plug_gen5_power_5

      - id: bryter_historikk
        type: history-graph
        title: 'bryter historikk'
        entities:
          - switch.fibaro_system_fgwpef_wall_plug_gen5_switch_3

#Serverstatus
  - id: Server_statuser
    title: Serverstatus
    cards:
    
      - id: server_status
        type: entities
        show_header_toggle: false
        title: System
        entities:
          - sensor.processor_use
          - sensor.load_1m
          - sensor.load_5m
          - sensor.load_15m
          - sensor.memory_use_percent
          - sensor.disk_use_percent_
          - sensor.last_boot

#Handleliste
  - id: handlelister
    title: Handleliste
    cards:

      - id: shopping_fjellet
        type: shopping-list
        show_header_toggle: false
        title: Fjellet

#Test
  - id: testetab
    title: Test
    cards:

      - id: testetermostat
        type: thermostat
        show_header_toggle: false
        entity: climate.Stue
