switch.fibaro_system_fgwpef_wall_plug_gen5_switch:
  ignored: false
  polling_intensity: 0
  friendly_name: plugger
sensor.aeotec_zw100_multisensor_6_burglar:
  ignored: false
  polling_intensity: 0
binary_sensor.aeotec_zw100_multisensor_6_sensor:
  ignored: false
  polling_intensity: 0
  #  hidden: true
binary_sensor.fibaro_system_fgsd002_smoke_sensor_sensor:
  ignored: false
  polling_intensity: 0
  #  hidden: true
sensor.aeotec_zw100_multisensor_6_luminance:
  ignored: false
  polling_intensity: 0
  #  hidden: true
