
 - alias: Check sensor value show notification
   trigger:
     platform: numeric_state
     entity_id: sensor.stue_temperature
     above: 35
   action:
     - service: persistent_notification.create
       data:
         message: "Sensor value greater then 35"
     - service: notify.telegram
       data:
         title: "send temperatur varsling"


 - alias: Varsling for utetemperatur
   trigger:
     platform: numeric_state
     entity_id: sensor.ute_temperature
     below: -10
   action:
     service: persistent_notification.create
     data:
       message: "Under -10 ute"

       ##Systemrelatert

 - alias: Endret IP addresse
   hide_entity: true
   trigger:
     platform: state
     entity_id: sensor.ip
   action:
     service: scripts.telegram_ip_fornyet

 - alias: gi IP addresse
   trigger:
     platform: event
     event_type: telegram_command
     event_data:
       command: '/ip'
   action:
     - service: telegram_bot.send_message
       data_template:
         target: '{{ trigger.event.data.user_id }}'
         message: '{{ states.sensor.ip_addresse.state }}'

 - alias: list banned
   trigger:
     platform: event
     event_type: telegram_command
     event_data:
       command: '/banned'
   action:
     - service: telegram_bot.send_message
       data_template:
         target: '{{ trigger.event.data.user_id }}'
         message: '{{ trigger.event.data.command }}'
    

 - alias: Login Failure
   trigger:
     platform: state
     entity_id: persistent_notification.httplogin
   condition:
     condition: template
     value_template: "{{ trigger.to_state.state != off }}"
   action:
     service: notify.Ola
     data:
       message: "Failed Home Assistant login attempt!"

#BRANNVARSLING
 - alias: Brannalarm stue
   trigger:
   - platform: state
     entity_id: sensor.smoke_sensor_smoke_stue_1
     to: '255'
   action:
   - service: notify.Terje
     data:
       title: "Brann!"
       message: "Brannalarm i stua"
   - service: notify.Ola
     data:
       title: "Brann!"
       message: "Brannalarm i stua"

 - alias: temperaturvarsel
   trigger:
     platform: numeric_state
     entity_id: sensor.smoke_sensor_temperature_stue
     above: 35
   action:
   - service: persistent_notification.create
     data:
       message: "Over 35 grader i stuetaket"
   - service: notify.Ola
     data:
       title: "temperaturvarsel"
       message: "temperatur i stuetaket over 35 grader"
   - service: notify.Terje
     data:
       title: "Temperaturvarsel !!TEST!!"
       message: "temperatur i stuetaket over 35 grader"

 - alias: Brannalarm loftstue
   trigger:
   - platform: state
     entity_id: sensor.smoke_sensor_smoke_loftstue_2
     to: '255'
   action:
   - service: notify.Terje
     data:
       title: "Brann!"
       message: "røykvarsler utløst i loftstua"
   - service: notify.Ola
     data:
       title: "Brann!"
       message: "røykvarsler utløst i loftstua"

####### Innbruddsalarm

 - alias: Alarm gang
   trigger:
     - platform: state
       entity_id: sensor.movement_hall
       to: 'Bevegelse'
   action:
     service: notify.Ola
     data:
       title: "Alarm!"
       message: "Bevegelse i gangen!"
