
 - alias: Check sensor value show notification
   trigger:
     platform: numeric_state
     entity_id: sensor.stue_temperature
     above: 22
   action:
     - service: persistent_notification.create
       data:
         message: "Sensor value greater then 22"
     - service: notify.telegram
       data:
         title: "send temperatur varsling"


 - alias: Varsling for utetemperatur
   trigger:
     platform: numeric_state
     entity_id: sensor.ute_temperature
     below: -10
   action:
     service: persistent_notification.create
     data:
       message: "Under -10 ute"

       ##Systemrelatert

 - alias: Endret IP addresse
   hide_entity: true
   trigger:
     platform: state
     entity_id: sensor.ip
   action:
     service: scripts.telegram_ip_fornyet

 - alias: gi IP addresse
   trigger:
     platform: event
     event_type: telegram_command
     event_data:
       command: '/ip'
   action:
     - service: telegram_bot.send_message
       data_template:
         target: '{{ trigger.event.data.user_id }}'
         message: '{{ states.sensor.ip_addresse.state }}'

 - alias: Login Failure
   trigger:
     platform: state
     entity_id: persistent_notification.httplogin
   condition:
     condition: template
     value_template: "{{ trigger.to_state.state != off }}"
   action:
     service: notify.Ola
     data:
       message: "Failed Home Assistant login attempt!"

#BRANNVARSLING
 - alias: Brannalarm stue
   trigger:
   - platform: state
     entity_id: sensor.smoke_sensor_alarm_level_stue
     to: '255'
   action:
   - service: notify.Terje
     data:
       title: "Brann!"
       message: "Brannalarm i stua"
   - service: notify.Ola
     data:
       title: "Brann!"
       message: "Brannalarm i stua"

