- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: memory_use_percent
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: network_in
      arg: wlan0
    - type: network_out
      arg: wlan0
    - type: processor_use
    - type: last_boot

- platform: command_line
  name: IP addresse
  entity_id: sensor.ip
  command: "curl ifconfig.me"
