- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: memory_use_percent
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot

- platform: command_line
  name: IP addresse
  entity_id: sensor.ip
  command: "curl ifconfig.me"

- platform: template
  sensors:
    smoke_sensor_stue_batteri:
      friendly_name: 'roykvarsler stue'
      value_template: '{{ states.zwave.smoke_sensor_stue_overordnet.attributes.battery_level }}'
      device_class: battery
      unit_of_measurement: '%'
    
    smoke_sensor_loftstue_batteri:
      friendly_name: 'roykvarsler loftstue'
      value_template: '{{ states.zwave.smoke_sensor_loftstue_overordnet.attributes.battery_level }}'
      device_class: battery
      unit_of_measurement: '%'

