- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: memory_use_percent
    - type: memory_free
    - type: processor_use
    - type: last_boot

- platform: command_line
  name: IP addresse
  entity_id: sensor.ip
  command: "curl ifconfig.me"

- platform: template
  sensors:
    smoke_sensor_stue_batteri:
      friendly_name: 'roykvarsler batteri stue'
      value_template: '{{ states.zwave.smoke_sensor_stue_overordnet.attributes.battery_level }}'
      device_class: battery
      unit_of_measurement: '%'
    
    smoke_sensor_loftstue_batteri:
      friendly_name: 'roykvarsler batteri loftstue'
      value_template: '{{ states.zwave.smoke_sensor_loftstue_overordnet.attributes.battery_level }}'
      device_class: battery
      unit_of_measurement: '%'

    smoke_sensor_loftstue_smoke:
      friendly_name: 'røykvarsler loftstue'
      value_template: >-
        {% if is_state("sensor.smoke_sensor_smoke_loftstue_2", "255") %}
          Alarm
        {% elif is_state("sensor.smoke_sensor_burglar_loftstue", "3") %}
          Demontert
        {% else %}
          Venter
        {% endif %}
    
    smoke_sensor_stue_smoke:
      friendly_name: 'røykvarsler stue'
      value_template: >-
        {% if is_state("sensor.smoke_sensor_smoke_stue_2", "255") %}
          Alarm
        {% elif is_state("sensor.smoke_sensor_burglar_stue", "3") %}
          Demontert
        {% else %}
          Venter
        {% endif %}

    movement_hall:
      friendly_name: 'Bevegelse gang'
      value_template: >-
        {% if is_state("sensor.aeotec_zw100_multisensor_6_burglar_3", "8") %}
          Bevegelse
        {% else %}
          Ingen bevegelse
        {% endif %}
